spring:
  main:
    log-startup-info: true
    banner-mode: console
  output:
    ansi:
      enabled: always
  data:
      mongodb:
        uri: ${MONGO}
        auto-index-creation: true
server:
  port: 8111